### ISSUE TITLE
Progress Tracking List

### ISSUE THREAD

**Issue by dathinaios** [haksanlulz/discworld-gcs-library#1]
I got this list from the GCA file so hopefully it is complete. We can tick off as we go along so we don't go over the same stuff.

## Meta Traits

- [ ] TE:Domestic Animal
- [ ] TE:Spirit
- [ ] TE:Wild Animal

## Advantages

- [ ] AD:_New Advantage
- [ ] AD:_New Leveled Advantage
- [ ] AD:_New Parent Item
- [ ] AD:_New Talent
- [ ] AD:Absolute Direction
- [ ] AD:Absolute Timing
- [ ] AD:Active IR
- [ ] AD:Acute Hearing
- [ ] AD:Acute Taste and Smell
- [ ] AD:Acute Touch
- [ ] AD:Acute Vision
- [ ] AD:Administrative Rank
- [ ] AD:Alternate Form
- [ ] AD:Alternate Identity
- [ ] AD:Ambidexterity
- [ ] AD:Amphibious
- [ ] AD:Animal Control Talent
- [ ] AD:Animal Empathy
- [ ] AD:Animal Friend
- [ ] AD:Appearance
- [ ] AD:Artificer
- [ ] AD:Born to Hang
- [ ] AD:Born War-Leader
- [ ] AD:Brachiator
- [ ] AD:Cast-Iron Stomach
- [ ] AD:Catfall
- [ ] AD:Channelling
- [ ] AD:Chaos Talent
- [ ] AD:Charisma
- [ ] AD:Chronolocation
- [ ] AD:Claim to Hospitality
- [ ] AD:Clairsentience
- [ ] AD:Claws (Blunt Claws)
- [ ] AD:Claws (Hooves)
- [ ] AD:Claws (Long Talons)
- [ ] AD:Claws (Sharp Claws)
- [ ] AD:Claws (Talons)
- [ ] AD:Clerical Investment
- [ ] AD:Clinging
- [ ] AD:Cold/Ice Talent
- [ ] AD:Combat Reflexes
- [ ] AD:Common Sense
- [ ] AD:Compartmentalized Mind
- [ ] AD:Constriction Attack
- [ ] AD:Contact
- [ ] AD:Control [Common]
- [ ] AD:Control [Godlike]
- [ ] AD:Control [Occasional]
- [ ] AD:Control [Rare]
- [ ] AD:Control [Very Common]
- [ ] AD:Corrosion Attack
- [ ] AD:Cosmic Talent
- [ ] AD:Crushing Attack
- [ ] AD:Cultural Familiarity (Native)
- [ ] AD:Cultural Familiarity
- [ ] AD:Cutting Attack
- [ ] AD:Damage Resistance
- [ ] AD:Danger Sense
- [ ] AD:Daredevil
- [ ] AD:Dark Vision
- [ ] AD:Darkness Talent
- [ ] AD:Death Talent
- [ ] AD:Destiny
- [ ] AD:Detect
- [ ] AD:Dimension Shift
- [ ] AD:Diplomatic Immunity
- [ ] AD:Discriminatory Smell
- [ ] AD:Doesn't Breathe
- [ ] AD:Doesn't Eat or Drink
- [ ] AD:Doesn't Sleep
- [ ] AD:Dominance
- [ ] AD:Double-Jointed
- [ ] AD:Duplication
- [ ] AD:Earth Talent
- [ ] AD:Eidetic Memory
- [ ] AD:Elastic Skin
- [ ] AD:Electricity Talent
- [ ] AD:Electrokinesis Talent
- [ ] AD:Empathy
- [ ] AD:Energy Reserve
- [ ] AD:Enhanced Block
- [ ] AD:Enhanced Dodge
- [ ] AD:Enhanced Move (Air)
- [ ] AD:Enhanced Move (Ground)
- [ ] AD:Enhanced Move (Water)
- [ ] AD:Enhanced Parry (%One-Handed Melee Weapon ArtList%)
- [ ] AD:Enhanced Parry (%One-Handed Melee WeaponList%)
- [ ] AD:Enhanced Parry (%One-Handed Melee Weapon SportList%)
- [ ] AD:Enhanced Parry (all parries)
- [ ] AD:Enhanced Parry (bare hands)
- [ ] AD:Enhanced Time Sense
- [ ] AD:Enhanced Tracking
- [ ] AD:Extra Attack
- [ ] AD:Extra Life
- [ ] AD:Fashion Sense
- [ ] AD:Fatigue Attack
- [ ] AD:Fearlessness
- [ ] AD:Filter Lungs
- [ ] AD:Flexibility
- [ ] AD:Flight
- [ ] AD:Flight (Levitation)
- [ ] AD:Flight (Winged, Can Hover)
- [ ] AD:Flight (Winged, Cannot Hover)
- [ ] AD:Gadgeteer
- [ ] AD:Gifted Artist
- [ ] AD:Gizmo
- [ ] AD:Good Talent
- [ ] AD:Gravity Talent
- [ ] AD:Green Thumb
- [ ] AD:Healer
- [ ] AD:Healing Talent
- [ ] AD:Healing
- [ ] AD:High Manual Dexterity
- [ ] AD:High Pain Threshold
- [ ] AD:High TL
- [ ] AD:Igor Immunity
- [ ] AD:Indomitable
- [ ] AD:Injury Tolerance
- [ ] AD:Insubstantiality
- [ ] AD:Intuitive Mathematician
- [ ] AD:Invisibility
- [ ] AD:Kinetic Energy Talent
- [ ] AD:Language - Native (Spoken)
- [ ] AD:Language - Native (Written)
- [ ] AD:Language - Native
- [ ] AD:Language (Spoken)
- [ ] AD:Language (Written)
- [ ] AD:Language Talent
- [ ] AD:Language
- [ ] AD:Legal Enforcement Powers
- [ ] AD:Legal Immunity
- [ ] AD:Less Sleep
- [ ] AD:Lifting ST
- [ ] AD:Lightning Calculator
- [ ] AD:Luck
- [ ] AD:Magery 0
- [ ] AD:Magery
- [ ] AD:Mathematical Ability
- [ ] AD:Medium
- [ ] AD:Metalwork
- [ ] AD:Military Rank
- [ ] AD:Mind Shield
- [ ] AD:Modified ST-Based Damage
- [ ] AD:Musical Ability
- [ ] AD:Night Vision
- [ ] AD:Outdoorsman
- [ ] AD:Patrons
- [ ] AD:Perfect Balance
- [ ] AD:Photographic Memory
- [ ] AD:Pitiable
- [ ] AD:Pressure-Proof
- [ ] AD:Protected Eyes
- [ ] AD:Rank
- [ ] AD:Rapid Healing
- [ ] AD:Regeneration
- [ ] AD:Regrowth
- [ ] AD:Religious Rank
- [ ] AD:Repairable
- [ ] AD:Reputation
- [ ] AD:Resistant
- [ ] AD:See Invisible (Magical)
- [ ] AD:See Invisible (Spirit)
- [ ] AD:Sensitive Touch
- [ ] AD:Sensitive
- [ ] AD:Serendipity
- [ ] AD:Silence
- [ ] AD:Single-Minded
- [ ] AD:Smooth Operator
- [ ] AD:Social Regard (Feared)
- [ ] AD:Social Regard (Respected)
- [ ] AD:Social Regard (Venerated)
- [ ] AD:Social Regard
- [ ] AD:Sonar
- [ ] AD:Speak With Animals
- [ ] AD:Spirit Empathy
- [ ] AD:Status
- [ ] AD:Super Climbing
- [ ] AD:Supernatural Durability
- [ ] AD:Swarm Body
- [ ] AD:Teeth (Blunt Teeth)
- [ ] AD:Teeth (Fangs)
- [ ] AD:Teeth (Sharp Beak)
- [ ] AD:Teeth (Sharp Teeth)
- [ ] AD:Temperature Tolerance (Cold)
- [ ] AD:Temperature Tolerance (Heat)
- [ ] AD:Tenure
- [ ] AD:True Faith
- [ ] AD:Ultrahearing
- [ ] AD:Unfazeable
- [ ] AD:Unkillable
- [ ] AD:Versatile
- [ ] AD:Versatile (Inspiration Magnet)
- [ ] AD:Very Rapid Healing
- [ ] AD:Voice
- [ ] AD:Watch Rank
- [ ] AD:Wealth

## Perks

- [ ] PE:_New Perk
- [ ] PE:Alcohol Tolerance
- [ ] PE:Archaic Training
- [ ] PE:Assassin in Good Standing
- [ ] PE:Autotrance
- [ ] PE:Blade-Proof Bare-Chestedness
- [ ] PE:Boredom Immunity
- [ ] PE:Check the Exits
- [ ] PE:Climatic Emphasis
- [ ] PE:Cobblestone Sense
- [ ] PE:Cold Resistance
- [ ] PE:Controllable Disadvantage
- [ ] PE:Crossbow Safety
- [ ] PE:Cutting-Edge Training
- [ ] PE:Deep Sleeper
- [ ] PE:Divine News-Feed
- [ ] PE:Dual Ready
- [ ] PE:Fearsome Stare
- [ ] PE:Feathers
- [ ] PE:Forgettable Face
- [ ] PE:Fully-Dressed Resurrection
- [ ] PE:Fur
- [ ] PE:Good with (Animal)
- [ ] PE:Good with (Social Group)
- [ ] PE:Haughty Sneer
- [ ] PE:Heartbeat Counter
- [ ] PE:Heat Resistance
- [ ] PE:High-Heeled Heroine
- [ ] PE:Honest Face
- [ ] PE:Hyper-Specialisation
- [ ] PE:Improvised Weapons
- [ ] PE:Limited Camouflage
- [ ] PE:Limited Camouflage (Stone)
- [ ] PE:Longevity
- [ ] PE:Name Hearing
- [ ] PE:No Hangover
- [ ] PE:Off-Hand Training
- [ ] PE:Oggham Reader
- [ ] PE:One Spell Doesn't Need Preparation
- [ ] PE:Penetrating Voice
- [ ] PE:Recognised Divinity
- [ ] PE:Sanitized Metabolism
- [ ] PE:Scales
- [ ] PE:Sea Legs
- [ ] PE:Secret Name
- [ ] PE:Shtick
- [ ] PE:Self-Styling Hair
- [ ] PE:Sordid Claws
- [ ] PE:Statuesque
- [ ] PE:Street Swagger
- [ ] PE:Striking Surface
- [ ] PE:There on Call
- [ ] PE:Understands the Librarian
- [ ] PE:Unfazed by Size

## Disadvantages

- [ ] DI:_New Disadvantage
- [ ] DI:_New Parent Item
- [ ] DI:Absent-Mindedness
- [ ] DI:Addiction ([Physiological])
- [ ] DI:Addiction ([Psychological])
- [ ] DI:Aerial
- [ ] DI:Alcoholism
- [ ] DI:Alcoholism (Withdrawn)
- [ ] DI:Amnesia (Partial)
- [ ] DI:Amnesia (Total)
- [ ] DI:Appearance
- [ ] DI:Bad Back
- [ ] DI:Bad Grip
- [ ] DI:Bad Sight (Farsighted)
- [ ] DI:Bad Sight (Nearsighted)
- [ ] DI:Bad Smell
- [ ] DI:Bad Temper
- [ ] DI:Berserk
- [ ] DI:Bestial
- [ ] DI:Blindness
- [ ] DI:Bloodlust
- [ ] DI:Bully
- [ ] DI:Callous
- [ ] DI:Cannot Kick
- [ ] DI:Cannot Learn
- [ ] DI:Cannot Speak
- [ ] DI:Charitable
- [ ] DI:Chummy
- [ ] DI:Clueless
- [ ] DI:Code of Honour (Chivalry)
- [ ] DI:Code of Honour (Gentleman's)
- [ ] DI:Code of Honour (Pirate's)
- [ ] DI:Code of Honour (Professional)
- [ ] DI:Code of Honour (Soldier's)
- [ ] DI:Code of Honour
- [ ] DI:Combat Paralysis
- [ ] DI:Compulsive Behaviour
- [ ] DI:Compulsive Carousing
- [ ] DI:Compulsive Gambling
- [ ] DI:Compulsive Generosity
- [ ] DI:Compulsive Lying
- [ ] DI:Compulsive Spending
- [ ] DI:Compulsive Vowing
- [ ] DI:Confused
- [ ] DI:Cowardice
- [ ] DI:Curious
- [ ] DI:Cursed
- [ ] DI:Deafness
- [ ] DI:Delusion
- [ ] DI:Dependent
- [ ] DI:Disciplines of Faith (Asceticism)
- [ ] DI:Disciplines of Faith (Monasticism)
- [ ] DI:Disciplines of Faith (Mysticism)
- [ ] DI:Disciplines of Faith (Ritualism)
- [ ] DI:Disciplines of Faith
- [ ] DI:Disturbing Voice
- [ ] DI:Dread
- [ ] DI:Duty
- [ ] DI:Dwarfish Greed
- [ ] DI:Dwarfism
- [ ] DI:Dyslexia
- [ ] DI:Easy to Read
- [ ] DI:Enemy (Formidable group)
- [ ] DI:Enemy (Group of less powerful people)
- [ ] DI:Enemy (One Person)
- [ ] DI:Faith Maintenance
- [ ] DI:Fanaticism
- [ ] DI:Fat
- [ ] DI:Fearfulness
- [ ] DI:Fragile
- [ ] DI:Frightens Animals
- [ ] DI:Gigantism
- [ ] DI:Gluttony
- [ ] DI:Greed
- [ ] DI:Gregarious
- [ ] DI:Gullibility
- [ ] DI:Ham-Fisted
- [ ] DI:Hard of Hearing
- [ ] DI:Hidebound
- [ ] DI:Honesty
- [ ] DI:Hunchback
- [ ] DI:Impulsiveness
- [ ] DI:Incurious
- [ ] DI:Indecisive
- [ ] DI:Innumerate
- [ ] DI:Insomniac
- [ ] DI:Intolerance
- [ ] DI:Jealousy
- [ ] DI:Kleptomania
- [ ] DI:Klutz
- [ ] DI:Lame
- [ ] DI:No Legs
- [ ] DI:Laziness
- [ ] DI:Lecherousness
- [ ] DI:Loner
- [ ] DI:Low Empathy
- [ ] DI:Low Pain Threshold
- [ ] DI:Low TL
- [ ] DI:Megalomania
- [ ] DI:Miserliness
- [ ] DI:Motion Sickness
- [ ] DI:Mute
- [ ] DI:Quadruped
- [ ] DI:No Sense of Humour
- [ ] DI:No Sense of Smell/Taste
- [ ] DI:Oblivious
- [ ] DI:Obsession
- [ ] DI:Odious Personal Habit
- [ ] DI:Odious Racial Habit
- [ ] DI:One Arm
- [ ] DI:One Eye
- [ ] DI:One Hand
- [ ] DI:Overconfidence
- [ ] DI:Overweight
- [ ] DI:Pacifism (Cannot Harm Innocents)
- [ ] DI:Pacifism (Reluctant Killer)
- [ ] DI:Pacifism (Self-Defence Only)
- [ ] DI:Paranoia
- [ ] DI:Phobia (%examplelist%)
- [ ] DI:Phobia
- [ ] DI:Post-Combat Shakes
- [ ] DI:Pyromania
- [ ] DI:Quadruped
- [ ] DI:Reputation
- [ ] DI:Restricted Diet
- [ ] DI:Restricted Vision
- [ ] DI:Revulsion
- [ ] DI:Sadism
- [ ] DI:Secret
- [ ] DI:Secret Identity (Normal Status)
- [ ] DI:Secret Identity (High Status)
- [ ] DI:Selfish
- [ ] DI:Selfless
- [ ] DI:Semi-Upright
- [ ] DI:Sense of Duty
- [ ] DI:Short Arms (1 Arm)
- [ ] DI:Short Arms (2 Arms)
- [ ] DI:Short Attention Span
- [ ] DI:Short Legs
- [ ] DI:Shyness
- [ ] DI:Skinny
- [ ] DI:Slow Eater
- [ ] DI:Slow Healing
- [ ] DI:Social Stigma (Criminal Record)
- [ ] DI:Social Stigma (Disowned)
- [ ] DI:Social Stigma (Excommunicated)
- [ ] DI:Social Stigma (Ignorant)
- [ ] DI:Social Stigma (Minor)
- [ ] DI:Social Stigma (Minority Group)
- [ ] DI:Social Stigma (Monster)
- [ ] DI:Social Stigma (Publically disowned)
- [ ] DI:Social Stigma (Second-Class Citizen)
- [ ] DI:Social Stigma (Subjugated)
- [ ] DI:Social Stigma (Uneducated)
- [ ] DI:Social Stigma (Valuable Property)
- [ ] DI:Social Stigma
- [ ] DI:Split Personality
- [ ] DI:Squeamish
- [ ] DI:Status
- [ ] DI:Stubbornness
- [ ] DI:Sulphurholism
- [ ] DI:Sulphurholism (Withdrawn)
- [ ] DI:Supernatural Feature
- [ ] DI:Supernatural Feature (Mostly Concealed: [Feature])
- [ ] DI:Supernatural Feature (Blatantly Unnatural: [Feature])
- [ ] DI:Supernatural Feature (Mostly Concealed: No Body Heat)
- [ ] DI:Supernatural Feature (Blatantly Unnatural: No Reflection)
- [ ] DI:Supernatural Feature (Blatantly Unnatural: No Shadow)
- [ ] DI:Supernatural Feature (Blatantly Unnatural: Deathly Pallor)
- [ ] DI:Trademark
- [ ] DI:Trickster
- [ ] DI:Total Vampire Nocturnalism
- [ ] DI:Troll Brain
- [ ] DI:Troll Nocturnalism
- [ ] DI:Truthfulness
- [ ] DI:Uncontrollable Appetite
- [ ] DI:Unhealing
- [ ] DI:Unique
- [ ] DI:Unluckiness
- [ ] DI:Unnatural Features
- [ ] DI:Unnaturally Fragile
- [ ] DI:Very Fat
- [ ] DI:Vow
- [ ] DI:Vulnerability
- [ ] DI:Weak Bite
- [ ] DI:Weakness
- [ ] DI:Wealth

## Quirks

- [ ] QU:_New Quirk
- [ ] QU:Alcohol Intolerance
- [ ] QU:Attentive
- [ ] QU:Autocondimentor
- [ ] QU:Blunt and Tactless
- [ ] QU:Bowlegged
- [ ] QU:Brawling Society
- [ ] QU:Broad-Minded
- [ ] QU:Cannot Float
- [ ] QU:Cannot Run Long Distances
- [ ] QU:Careful
- [ ] QU:Chauvinistic
- [ ] QU:Closes Eyes and Screams to Intimidate Victims
- [ ] QU:Code of Honour
- [ ] QU:Collects Own Snot and Earwax
- [ ] QU:Congenial
- [ ] QU:Considers Dwarf Gender a Very Private Matter
- [ ] QU:Delusion
- [ ] QU:Delusion (Spelling my name backwards disguises it perfectly)
- [ ] QU:Dislikes [specify]
- [ ] QU:Dislikes Cramped Conditions
- [ ] QU:Dislikes Garlic
- [ ] QU:Dislikes Water
- [ ] QU:Distinctive Feature
- [ ] QU:Distractible
- [ ] QU:Doesn't Go Where Not Asked
- [ ] QU:Doggy Responses
- [ ] QU:Dreamer
- [ ] QU:Dull
- [ ] QU:Expression
- [ ] QU:Former Alcoholic
- [ ] QU:Former Sulphurholic
- [ ] QU:Giggles a Lot
- [ ] QU:Habit
- [ ] QU:Horrible Hangovers
- [ ] QU:Humble
- [ ] QU:Hunter's Habits
- [ ] QU:Imaginative
- [ ] QU:Likes
- [ ] QU:Minor Handicap
- [ ] QU:Nervous Stomach
- [ ] QU:No Staff
- [ ] QU:Nosy
- [ ] QU:Obsession
- [ ] QU:Personality Change
- [ ] QU:Personality Change (Gains Bad Temper When Drinking)
- [ ] QU:Prefers To Be Above Ground Level
- [ ] QU:Proud
- [ ] QU:Reflexively Grabs and Consumes Small Flying Creatures
- [ ] QU:Responsive
- [ ] QU:Short Lifespan
- [ ] QU:Silver Aversion
- [ ] QU:Staid
- [ ] QU:Sunburns Easily
- [ ] QU:Terrifying Singer
- [ ] QU:Touchy About Height and Beard
- [ ] QU:Uncongenial
- [ ] QU:Vow
- [ ] QU:Weak Spot

## Skills
- [ ] SK:Accounting
- [ ] SK:Acrobatics
- [ ] SK:Acting
- [ ] SK:Administration
- [ ] SK:Aerobatics
- [ ] SK:Airshipman
- [ ] SK:Alchemy
- [ ] SK:Animal Handling
- [ ] SK:Animal Handling (Big Cats)
- [ ] SK:Animal Handling (Dogs)
- [ ] SK:Animal Handling (Equines)
- [ ] SK:Animal Handling (Raptors)
- [ ] SK:Anthropology
- [ ] SK:Aquabatics
- [ ] SK:Archaeology
- [ ] SK:Architecture
- [ ] SK:Area Knowledge
- [ ] SK:Armoury
- [ ] SK:Armoury (Body Armour)
- [ ] SK:Armoury (Heavy Weapons)
- [ ] SK:Armoury (Melee Weapons)
- [ ] SK:Armoury (Missile Weapons)
- [ ] SK:Artillery
- [ ] SK:Artillery (Cannon)
- [ ] SK:Artillery (Catapult)
- [ ] SK:Artist
- [ ] SK:Artist (Body Art)
- [ ] SK:Artist (Calligraphy)
- [ ] SK:Artist (Drawing)
- [ ] SK:Artist (Illumination)
- [ ] SK:Artist (Illusion)
- [ ] SK:Artist (Interior Decorating)
- [ ] SK:Artist (Painting)
- [ ] SK:Artist (Pottery)
- [ ] SK:Artist (Scene Design)
- [ ] SK:Artist (Sculpting)
- [ ] SK:Artist (Woodworking)
- [ ] SK:Astronomy
- [ ] SK:Astronomy (Observational)
- [ ] SK:Autohypnosis
- [ ] SK:Axe/Mace
- [ ] SK:Bicycling
- [ ] SK:Blowpipe
- [ ] SK:Boating
- [ ] SK:Boating (Sailboat)
- [ ] SK:Boating (Unpowered)
- [ ] SK:Body Language
- [ ] SK:Body Sense
- [ ] SK:Bow
- [ ] SK:Boxing
- [ ] SK:Brawling
- [ ] SK:Broadsword
- [ ] SK:Camouflage
- [ ] SK:Carousing
- [ ] SK:Carpentry
- [ ] SK:Cartography
- [ ] SK:Chemistry
- [ ] SK:Climbing
- [ ] SK:Cloak
- [ ] SK:Computer Hacking
- [ ] SK:Computer Operation
- [ ] SK:Computer Programming
- [ ] SK:Conducting
- [ ] SK:Connoisseur
- [ ] SK:Connoisseur (Dance)
- [ ] SK:Connoisseur (Literature)
- [ ] SK:Connoisseur (Music)
- [ ] SK:Connoisseur (Visual Arts)
- [ ] SK:Connoisseur (Wine)
- [ ] SK:Cooking
- [ ] SK:Counterfeiting
- [ ] SK:Criminology
- [ ] SK:Crossbow
- [ ] SK:Cryptography
- [ ] SK:Current Affairs
- [ ] SK:Current Affairs (Business)
- [ ] SK:Current Affairs (Headline News)
- [ ] SK:Current Affairs (Politics)
- [ ] SK:Current Affairs (Regional: [Regional])
- [ ] SK:Current Affairs (Sports)
- [ ] SK:Dancing
- [ ] SK:Detect Lies
- [ ] SK:Diagnosis
- [ ] SK:Diplomacy
- [ ] SK:Directing
- [ ] SK:Disguise
- [ ] SK:Driving
- [ ] SK:Driving (Automobile)
- [ ] SK:Driving (Construction Equipment)
- [ ] SK:Driving (Halftrack)
- [ ] SK:Driving (Heavy Wheeled)
- [ ] SK:Driving (Hovercraft)
- [ ] SK:Driving (Locomotive)
- [ ] SK:Driving (Mecha)
- [ ] SK:Driving (Motorcycle)
- [ ] SK:Driving (Tracked)
- [ ] SK:Engineer
- [ ] SK:Engineer (Animal-Drawn Vehicles)
- [ ] SK:Engineer (Artillery)
- [ ] SK:Engineer (Bicycles)
- [ ] SK:Engineer (Civil)
- [ ] SK:Engineer (Clacks)
- [ ] SK:Engineer (Clockwork)
- [ ] SK:Engineer (Combat)
- [ ] SK:Engineer (Low-Tech Machines)
- [ ] SK:Engineer (Magical)
- [ ] SK:Engineer (Mining)
- [ ] SK:Engineer (Ships)
- [ ] SK:Engineer (Steam Engines)
- [ ] SK:Escape
- [ ] SK:Explosives
- [ ] SK:Explosives (Demolition)
- [ ] SK:Explosives (Fireworks)
- [ ] SK:Falconry
- [ ] SK:Farming
- [ ] SK:Fast-Draw
- [ ] SK:Fast-Draw (Arrow)
- [ ] SK:Fast-Draw (Knife)
- [ ] SK:Fast-Draw (Long Arm)
- [ ] SK:Fast-Draw (Pistol)
- [ ] SK:Fast-Draw (Sword)
- [ ] SK:Fast-Draw (Two-Handed Sword)
- [ ] SK:Fast-Talk
- [ ] SK:Filch
- [ ] SK:Finance
- [ ] SK:Fire Eating
- [ ] SK:First Aid
- [ ] SK:Fishing
- [ ] SK:Flail
- [ ] SK:Flamethrower
- [ ] SK:Forced Entry
- [ ] SK:Forensics
- [ ] SK:Forgery
- [ ] SK:Fortune-Telling
- [ ] SK:Fortune-Telling (Astrology)
- [ ] SK:Fortune-Telling (Augury)
- [ ] SK:Fortune-Telling (Crystal Gazing)
- [ ] SK:Fortune-Telling (Dream Interpretation)
- [ ] SK:Fortune-Telling (Feng Shui)
- [ ] SK:Fortune-Telling (Palmistry)
- [ ] SK:Fortune-Telling (Tarot)
- [ ] SK:Forward Observer
- [ ] SK:Free Fall
- [ ] SK:Freight Handling
- [ ] SK:Gambling
- [ ] SK:Games
- [ ] SK:Gardening
- [ ] SK:Geology
- [ ] SK:Gesture
- [ ] SK:Gunner
- [ ] SK:Gunner (Cannon)
- [ ] SK:Gunner (Catapult)
- [ ] SK:Guns
- [ ] SK:Guns (Pistol)
- [ ] SK:Guns (Rifle)
- [ ] SK:Guns (Shotgun)
- [ ] SK:Heraldry
- [ ] SK:Herb Lore
- [ ] SK:Hidden Lore
- [ ] SK:Hidden Lore (Conspiracies)
- [ ] SK:Hidden Lore (Demon Lore)
- [ ] SK:Hidden Lore (Faerie Lore)
- [ ] SK:Hidden Lore (Spirit Lore)
- [ ] SK:Hiking
- [ ] SK:History
- [ ] SK:Hobby Skill
- [ ] SK:Holdout
- [ ] SK:Housekeeping
- [ ] SK:Hypnotism
- [ ] SK:Innate Attack
- [ ] SK:Innate Attack (Beam)
- [ ] SK:Innate Attack (Breath)
- [ ] SK:Innate Attack (Gaze)
- [ ] SK:Innate Attack (Projectile)
- [ ] SK:Intelligence Analysis
- [ ] SK:Interrogation
- [ ] SK:Intimidation
- [ ] SK:Jeweler
- [ ] SK:Judo
- [ ] SK:Jumping
- [ ] SK:Karate
- [ ] SK:Kiai
- [ ] SK:Knife
- [ ] SK:Knot-Tying
- [ ] SK:Kusari
- [ ] SK:Lance
- [ ] SK:Lasso
- [ ] SK:Law
- [ ] SK:Leadership
- [ ] SK:Leatherworking
- [ ] SK:Lifting
- [ ] SK:Light Walk
- [ ] SK:Linguistics
- [ ] SK:Lip Reading
- [ ] SK:Literature
- [ ] SK:Lockpicking
- [ ] SK:Makeup
- [ ] SK:Masonry
- [ ] SK:Mathematics
- [ ] SK:Mathematics (Applied)
- [ ] SK:Mathematics (Pure)
- [ ] SK:Mechanic
- [ ] SK:Meditation
- [ ] SK:Merchant
- [ ] SK:Metallurgy
- [ ] SK:Meteorology
- [ ] SK:Mimicry
- [ ] SK:Mimicry (Animal Sounds)
- [ ] SK:Mimicry (Bird Calls)
- [ ] SK:Mimicry (Speech)
- [ ] SK:Mount
- [ ] SK:Musical Composition
- [ ] SK:Musical Instrument
- [ ] SK:Naturalist
- [ ] SK:Navigation
- [ ] SK:Navigation (Air)
- [ ] SK:Navigation (Land)
- [ ] SK:Navigation (Sea)
- [ ] SK:Observation
- [ ] SK:Occultism
- [ ] SK:Packing
- [ ] SK:Panhandling
- [ ] SK:Performance
- [ ] SK:Philosophy
- [ ] SK:Photography
- [ ] SK:Physician
- [ ] SK:Physiology
- [ ] SK:Pickpocket
- [ ] SK:Piloting
- [ ] SK:Poetry
- [ ] SK:Poisons
- [ ] SK:Polearm
- [ ] SK:Politics
- [ ] SK:Pot-Making
- [ ] SK:Professional Skill
- [ ] SK:Professional Skill (Barber)
- [ ] SK:Professional Skill (Brewer)
- [ ] SK:Professional Skill (Choreographer)
- [ ] SK:Professional Skill (Cooper)
- [ ] SK:Professional Skill (Distiller)
- [ ] SK:Professional Skill (Dyer)
- [ ] SK:Professional Skill (Florist)
- [ ] SK:Professional Skill (Game Designer)
- [ ] SK:Professional Skill (Glassblower)
- [ ] SK:Professional Skill (Leatherworking)
- [ ] SK:Professional Skill (Masonry)
- [ ] SK:Professional Skill (Potter)
- [ ] SK:Professional Skill (Prostitute)
- [ ] SK:Professional Skill (Tailor)
- [ ] SK:Professional Skill (Tanner)
- [ ] SK:Professional Skill (Vinter)
- [ ] SK:Professional Skill (Weaver)
- [ ] SK:Propaganda
- [ ] SK:Prospecting
- [ ] SK:Psychology
- [ ] SK:Public Speaking
- [ ] SK:Rapier
- [ ] SK:Religious Ritual
- [ ] SK:Research
- [ ] SK:Riding
- [ ] SK:Ritual Magic
- [ ] SK:Running
- [ ] SK:Savoir-Faire
- [ ] SK:Savoir-Faire (High Society)
- [ ] SK:Savoir-Faire (Military)
- [ ] SK:Savoir-Faire (Organised Crime)
- [ ] SK:Savoir-Faire (Servant)
- [ ] SK:Savoir-Faire (Watch)
- [ ] SK:Scrounging
- [ ] SK:Scuba
- [ ] SK:Seamanship
- [ ] SK:Search
- [ ] SK:Sewing
- [ ] SK:Sex Appeal
- [ ] SK:Shadowing
- [ ] SK:Shield
- [ ] SK:Shiphandling
- [ ] SK:Shortsword
- [ ] SK:Singing
- [ ] SK:Skating
- [ ] SK:Sleight of Hand
- [ ] SK:Sling
- [ ] SK:Smallsword
- [ ] SK:Smith
- [ ] SK:Smith (Blacksmith)
- [ ] SK:Smith (Coppersmith)
- [ ] SK:Smith (Tinsmith)
- [ ] SK:Smuggling
- [ ] SK:Sociology
- [ ] SK:Soldier
- [ ] SK:Spacer
- [ ] SK:Spear
- [ ] SK:Spear Thrower
- [ ] SK:Sports
- [ ] SK:Staff
- [ ] SK:Stealth
- [ ] SK:Strategy
- [ ] SK:Strategy (Land)
- [ ] SK:Strategy (Naval)
- [ ] SK:Streetwise
- [ ] SK:Submarine
- [ ] SK:Surgery
- [ ] SK:Survival
- [ ] SK:Survival (Arctic)
- [ ] SK:Survival (Desert)
- [ ] SK:Survival (Island/Beach)
- [ ] SK:Survival (Jungle)
- [ ] SK:Survival (L-Space)
- [ ] SK:Survival (Mountain)
- [ ] SK:Survival (Plains)
- [ ] SK:Survival (Swampland)
- [ ] SK:Survival (Woodlands)
- [ ] SK:Swimming
- [ ] SK:Symbol Drawing
- [ ] SK:Tactics
- [ ] SK:Teaching
- [ ] SK:Teamster
- [ ] SK:Thaumatology
- [ ] SK:Theology
- [ ] SK:Throwing
- [ ] SK:Thrown Weapon
- [ ] SK:Thrown Weapon (Axe/Mace)
- [ ] SK:Thrown Weapon (Knife)
- [ ] SK:Thrown Weapon (Spear)
- [ ] SK:Thrown Weapon (Stick)
- [ ] SK:Thrown Weapon (Throwing Star)
- [ ] SK:Tracking
- [ ] SK:Traps
- [ ] SK:Two-Handed Axe/Mace
- [ ] SK:Two-Handed Sword
- [ ] SK:Urban Survival
- [ ] SK:Veterinary
- [ ] SK:Weather Sense
- [ ] SK:Wrestling
- [ ] SK:Writing
